### ISSUE TITLE
Improve Weather App Code Readability and Error Handling in JavaScript/weatherApp/script.js

### ISSUE THREAD

**Issue by Amansingh0807** [ZeeshanMukhtar1/OpenVerse#102]
The current weather app code can be optimized for better readability, input validation, and error handling. 
Below are the proposed improvements:

**Issues Identified:**

- Variable Naming: Rename serchBox and serchBtn to searchBox and searchBtn.
- Input Validation: Add a check to prevent empty API calls.
- Clear Previous Data: Clear old error messages and weather data on new searches.
- Code Readability: Store repeated document.querySelector calls in variables.

**Proposed Changes:**

- Rename variables for clarity.
- Add input validation alert for empty searches.
- Clear previous messages and data on new searches.
- Simplify code with reusable variables for selectors.

**Comment by ZeeshanMukhtar1** [comment]
closes #106
