### ISSUE TITLE
Improve Quiz Code: Variable Naming, Input Validation, and Clear Previous Data in JavaScript/Quiz App/script.js

### ISSUE THREAD

**Issue by Amansingh0807** [ZeeshanMukhtar1/OpenVerse#103]
The current quiz code could benefit from the following improvements:

**1. Variable Naming Consistency:** Ensure variables have clear, consistent names for readability.
**2. Result Display Reset:** Previous result messages (e.g., "Correct!" or "Incorrect!") should be cleared before showing the next question to prevent overlap.
**3. Correct correctAnswer Index:** Update the correctAnswer index for the "strict equality" question from 3 to 1, as === is the correct operator for strict equality in JavaScript.
**4. Show Final Celebration:** Adjust final celebration logic to activate if the score is greater than 7 and ensure it disappears after 5 seconds.

**Proposed Solution:**

1. Update resultText clearing logic within the displayQuestion function.
2. Ensure variable names are consistent and self-explanatory.
3. Correct the answer index for strict equality in the quiz question object.
4. Add celebration display logic in showFinalResult with a timer to hide it after 5 seconds.

**Comment by ZeeshanMukhtar1** [comment]
closes #105
