### ISSUE TITLE
contact info should open in new page 

### ISSUE THREAD

**Issue by its-Pratik-15** [ZeeshanMukhtar1/OpenVerse#64]
if you assign me i will add it also add hacktoberfest tag to it

**Comment by ZeeshanMukhtar1** [comment]
Hi @its-Pratik-15 ,
Please note that the screenshot you provided is from the website showcasing our contributors, which is a separate site. To contribute to `OpenVerse`, you need to clone the [repo](https://github.com/ZeeshanMukhtar1/OpenVerse) and make your contributions there. 

Note: Every small contribution is welcome, as long as it adds value.
