### ISSUE TITLE
Counter Application in React JS

### ISSUE THREAD

**Issue by abhay-dev2901** [ZeeshanMukhtar1/OpenVerse#69]
Hi @ZeeshanMukhtar1 planning to add a Counter application in React to this repository please assign me this task and consider it under hactoberfest 2024. Ill be gald to have your quick response.

**Comment by ZeeshanMukhtar1** [comment]
Hi @abhay-dev2901  , You can proceed now !

**Comment by abhay-dev2901** [comment]
@ZeeshanMukhtar1 Please refer to PR #71 .
