### ISSUE TITLE
Hover Behavior and Color Reset for Elements

### ISSUE THREAD

**Issue by Shreyhac** [ZeeshanMukhtar1/OpenVerse#80]
When hovering over specific elements, the hovered element remains in its original color, which is expected. However, the other elements do not revert to their original color as intended. Instead, they stay in black and white, which disrupts the intended color scheme.

Expected Behavior
On Hover: When hovering over an element, it should retain its original color.
Other Elements: All other elements should revert to their original colors instead of black and white.

<img width="377" alt="Screenshot 2024-10-30 at 02 35 46" src="https://github.com/user-attachments/assets/080d36d6-a0bf-4b5d-adf1-69234caffd2f">

**Comment by Shreyhac** [comment]
@vamus092 please assign me this for the time being, will finish updating this project on the same day itself within 1-2 hours , right now im unable to add the hactoberfest label , u only please assign me this under hactoberfest

**Comment by Sushantjarial** [comment]
just do the work and make the pull request if it is correct the maintainer will add it

**Comment by ZeeshanMukhtar1** [comment]
Hi @Sushantjarial  ,
Please note that the issue you proposed is from the website showcasing our contributors, which is a separate site. To contribute to OpenVerse, you need to clone the [repo](https://github.com/ZeeshanMukhtar1/OpenVerse) and make your contributions there.

Note: Every small contribution is welcome, as long as it adds value.

**Comment by Sushantjarial** [comment]
> Hi @Sushantjarial  ,
> Please note that the issue you proposed is from the website showcasing our contributors, which is a separate site. To contribute to OpenVerse, you need to clone the [repo](https://github.com/ZeeshanMukhtar1/OpenVerse) and make your contributions there.
> 
> Note: Every small contribution is welcome, as long as it adds value.

Hi @ZeeshanMukhtar1 
> I think you should add the website code to this repo too so that community can also contribute to it. 
> Can you tell me are you updating the contributor's list manually or using GitHub api for it.
