### ISSUE TITLE
Alignment of searchbar

### ISSUE THREAD

**Issue by AayushhGoyal** [ZeeshanMukhtar1/OpenVerse#87]
## Issue
The search bar at left looks off in smaller devices i can get it fixed 

![image](https://github.com/user-attachments/assets/bae7a7dd-09c0-4b72-9762-6c74f98b2bfb)

**Comment by AayushhGoyal** [comment]
please assign me on this one @ZeeshanMukhtar1

**Comment by ZeeshanMukhtar1** [comment]
Hi @AayushhGoyal  ,
Please note that the issue you proposed is from the website showcasing our contributors, which is a separate site. To contribute to `OpenVerse`, you need to clone the [repo](https://github.com/ZeeshanMukhtar1/OpenVerse) and make your contributions there. 

Note: Every small contribution is welcome, as long as it adds value.

**Comment by AayushhGoyal** [comment]
Dalle bkl main hacktober ke liye kar rha hu tu saale invalid tag kya daal rha hai
