### ISSUE TITLE
Add Audio Adjuster Application in Python

### ISSUE THREAD

**Issue by Vandana029** [ZeeshanMukhtar1/OpenVerse#96]
I would like to propose the addition of an Audio Adjuster application to the project. This application allows users to play audio files, control playback speed, pause, and reset the audio.

**Key Features**:
- **File Selection**: Users can select audio files (MP3 format) from a directory.
- **Playback Control**: Options to play, pause, resume, and reset the audio playback.
- **Playback Speed Adjustment**: A slider to adjust the playback speed (50% to 150%).
- **User Interface**: A simple and intuitive interface built with PyQt6.

Could you please add the hacktoberfest label to this issue so that it can be considered for Hacktoberfest contributions? Thank you!

**Comment by ZeeshanMukhtar1** [comment]
Hi @Vandana029 , Hey! I’ve merged your PR; please start the repo and follow my account. Thanks!

**Comment by Vandana029** [comment]
Hi @ZeeshanMukhtar1, Thanks a lot for merging my PR. BTW could you tell me what's the meaning of starting the repo? Sorry for silly doubt as this is my first time contributing.

**Comment by ZeeshanMukhtar1** [comment]
> Hi @ZeeshanMukhtar1, Thanks a lot for merging my PR. BTW could you tell me what's the meaning of starting the repo? Sorry for silly doubt as this is my first time contributing.

Starting the repo helps rank it up for others, increasing its visibility—let me know if you need any assistance!
